# Generated by Django 3.0.6 on 2021-05-18 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='person',
            new_name='user_profile',
        ),
    ]
