# Generated by Django 3.0.6 on 2021-05-19 21:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20210520_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerslogin',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='managerslogin',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Manager'),
        ),
        migrations.AlterField(
            model_name='managerslogin',
            name='logged_in_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
