# Generated by Django 3.0.6 on 2021-05-19 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20210520_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerslogin',
            name='manager',
        ),
    ]
